/*! Copyright 2026 David Borske. All rights reserved. */
import{today as m,weekStart as h,isoDay as v,FLAG_RULE as g,isOff as D}from"./model.js";const f="D",w=50;function r(t){return Number(t)||0}function $(t){let o=0,a=0;return(t||[]).forEach(e=>{o+=r(e.d),a+=r(e.sale)}),{d:o,sale:a}}function x(t,o){const a=$(t.entries&&t.entries[o]);if(a.d>=w&&a.sale>0)return a.d/a.sale;if(g.set)return g.contactsPerSale;let e=0,p=0;return Object.keys(t.entries||{}).forEach(s=>{const i=$(t.entries[s]);e+=i.d,p+=i.sale}),e>=w&&p>0?e/p:null}function k(t,o){const a=t.goals&&t.goals[o];if(a)return Math.max(1,Math.round(r(a))||1);const e=t.dayGoal;return e&&e.rep===o?Math.max(1,Math.round(r(e.n))||1):1}function S(t,o){let a=null,e=0;const p=m();return(t.entries&&t.entries[o]||[]).forEach(s=>{r(s.d)>e&&(e=r(s.d)),s.date!==p&&r(s.sale)>0&&(!a||r(s.sale)>a.sale)&&(a={sale:r(s.sale),date:s.date})}),{best:a,maxD:e}}const E=[{k:"dp",name:"D to presentation rate",top:"p",bot:"d",min:15},{k:"pc",name:"ask rate",top:"c",bot:"p",min:5},{k:"cs",name:"close rate",top:"sale",bot:"c",min:5}];function M(t,o){const a=h(m()),e=h(v(new Date(new Date(a+"T12:00:00").getTime()-7*864e5))),p=(n,b)=>{const l={d:0,p:0,c:0,sale:0};return(t.entries&&t.entries[o]||[]).forEach(u=>{u.date>=n&&u.date<b&&(l.d+=r(u.d),l.p+=r(u.p),l.c+=r(u.c),l.sale+=r(u.sale))}),l},s=p(e,a),i=p(a,"9999");let c=null;if(E.forEach(n=>{if(s[n.bot]<n.min||i[n.bot]<n.min)return;const b=s[n.top]/s[n.bot],l=i[n.top]/i[n.bot],u=l-b;u>=.05&&(!c||u>c.up)&&(c={r:n,ra:b,rb:l,up:u})}),!c)return"";const d=n=>Math.round(Math.min(1,n)*100)+"%";return"Your "+c.r.name+" is up from "+d(c.ra)+" last week to "+d(c.rb)+" this week."}function T(t){return new Date(t+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"})}function O(t,o,a){const e=k(t,o),p=x(t,o),s=p?Math.max(1,Math.round(e*p)):0,i=r(a&&a.d),c=r(a&&a.sale),{best:d,maxD:n}=S(t,o),b=n>=10&&s>n;let l;c>=e?l="Goal met. Every "+f+" now is a bonus.":s?i>=s?l="You did your part. Sales follow the work. Keep going.":i===0?l=(b?"That is your biggest day yet. ":"")+"About "+s+" "+f+" gets you there.":l=(c>0?"Sale. Your averages are working. ":"")+i+" "+f+" done. About "+(s-i)+" more for your goal.":l=(c>0?"Sale. Your averages are working. ":"")+"Every conversation counts.";const u=d&&c>d.sale?`<p class="goalbest goalnew">New personal best: ${c} sales today.</p>`:d?`<p class="goalbest">Your best day: ${d.sale} sale${d.sale===1?"":"s"}, ${Y(T(d.date))}.</p>`:"",y=M(t,o);return`<div class="goalbox">
    <div class="goalrow goalsales"><span class="goall">Sales today</span><b class="goaln goalnow">${c}</b></div>
    <div class="goalrow"><span class="goall">Your goal</span><span class="goalstep">
      <button type="button" class="goalbtn" data-goal="${Math.max(1,e-1)}" aria-label="One less sale"${e<=1?" disabled":""}>&minus;</button>
      <b class="goaln" aria-live="polite">${e}</b>
      <button type="button" class="goalbtn" data-goal="${e+1}" aria-label="One more sale">+</button>
    </span></div>
    <p class="goalline" aria-live="polite">${l}</p>
    ${u}
    ${y?`<p class="goalbest">${y}</p>`:""}
    ${g.set&&g.contactsPerDay>0&&i<g.contactsPerDay&&!D(o,m())?`<p class="goalbest">Team pace: at least ${g.contactsPerDay} ${f} a day. You are at ${i}.</p>`:""}
  </div>`}function Y(t){return String(t??"").replace(/[&<>"']/g,o=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[o])}export{f as L,x as dPerSale,k as goalFor,O as goalHtml,M as progressLine};
